# Generated by Django 4.2.7 on 2023-11-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltd', models.CharField()),
                ('lng', models.CharField()),
                ('street_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filials', to='filial.address')),
            ],
        ),
        migrations.CreateModel(
            name='Kassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_operacionist', models.BooleanField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filials', to='filial.filial')),
            ],
        ),
    ]
